"""Generate the human- and machine-readable source manifests.

The manifests are produced from `data/processed/chunks.jsonl`, never from the live scraper,
so they describe exactly what was indexed. That matters for reproducibility: if a snapshot
has since changed on the web, the manifest still matches the index that produced the
answers, and a mismatch is a signal to re-run `--stage all`.
"""

from __future__ import annotations

import csv
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from src.config import get_settings
from src.paths import CHUNKS_PATH, DOCS_DIR
from src.types import Chunk

CSV_PATH = DOCS_DIR / "sources.csv"
MD_PATH = DOCS_DIR / "sources.md"

SOURCES_CSV_HEADER = (
    "source_id",
    "publisher",
    "scheme_id",
    "scheme_name",
    "category",
    "doc_type",
    "source_url",
    "retrieved_at",
    "chunk_count",
    "token_total",
    "token_min",
    "token_max",
)


@dataclass(frozen=True)
class SourceRow:
    """One source document, aggregated from every chunk it produced."""

    source_id: str
    publisher: str
    scheme_id: str
    scheme_name: str
    category: str
    doc_type: str
    source_url: str
    retrieved_at: str
    chunk_count: int
    token_total: int
    token_min: int
    token_max: int

    def as_csv(self) -> dict:
        return {key: getattr(self, key) for key in SOURCES_CSV_HEADER}


def aggregate(chunks: list[Chunk]) -> list[SourceRow]:
    """Group chunks by document. `source_id` is the chunk id minus its `__NNNN` suffix, so
    the key survives a re-chunk even when the individual chunk ids shift."""
    grouped: dict[str, list[Chunk]] = {}
    for chunk in chunks:
        grouped.setdefault(chunk.chunk_id.rsplit("__", 1)[0], []).append(chunk)

    rows: list[SourceRow] = []
    for source_id, group in sorted(grouped.items()):
        # Fields are document-level, so take them from the first chunk rather than
        # assuming the whole group agrees; the build guarantees it does.
        head = group[0]
        tokens = [c.token_count for c in group]
        rows.append(
            SourceRow(
                source_id=source_id,
                publisher=head.publisher,
                scheme_id=head.scheme_id,
                scheme_name=head.scheme_name,
                category=head.category,
                doc_type=head.doc_type,
                source_url=head.source_url,
                retrieved_at=head.retrieved_at,
                chunk_count=len(group),
                token_total=sum(tokens),
                token_min=min(tokens),
                token_max=max(tokens),
            )
        )
    return rows


def _md_escape(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(rows: list[SourceRow], chunks: list[Chunk]) -> str:
    """Render the manifest as Markdown, with the corpus totals a reviewer checks first."""
    hosts = Counter()
    for chunk in chunks:
        host = chunk.source_url.split("//", 1)[-1].split("/", 1)[0]
        hosts[host] += 1

    tokens = [c.token_count for c in chunks] or [0]
    lines = [
        "# Source manifest",
        "",
        "Generated by `python -m src.ingest.build_index --stage export`. Do not edit by hand:",
        "the file is rebuilt from the indexed corpus, so it always describes the exact chunks",
        "the bot answers from.",
        "",
        "## Corpus at a glance",
        "",
        f"- Documents: **{len(rows)}**",
        f"- Chunks: **{len(chunks)}**",
        f"- Tokens: **{sum(tokens)}** total, min {min(tokens)}, max {max(tokens)}",
        f"- Collection: `{get_settings().collection_name}`",
        f"- Embedding model: `{get_settings().embedding_model}`",
        f"- Retrieval: `TOP_K={get_settings().top_k}`, "
        f"`MIN_SIMILARITY={get_settings().min_similarity}`",
        "",
        "## Chunks by host",
        "",
        "| Host | Chunks |",
        "| --- | ---: |",
    ]
    for host, count in sorted(hosts.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{host}` | {count} |")

    lines += [
        "",
        "## Chunks by document type",
        "",
        "| Document type | Chunks |",
        "| --- | ---: |",
    ]
    for doc_type, count in sorted(Counter(c.doc_type for c in chunks).items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{doc_type}` | {count} |")

    lines += [
        "",
        "## Chunks by scheme",
        "",
        "| Scheme | Name | Chunks |",
        "| --- | --- | ---: |",
    ]
    by_scheme: dict[str, list[SourceRow]] = {}
    for row in rows:
        by_scheme.setdefault(row.scheme_id, []).append(row)
    for scheme_id, group in sorted(by_scheme.items()):
        name = group[0].scheme_name
        lines.append(
            f"| `{scheme_id}` | {_md_escape(name)} | {sum(r.chunk_count for r in group)} |"
        )

    lines += [
        "",
        "## Every document",
        "",
        "| Source | Publisher | Scheme | Type | Chunks | Tokens | Retrieved |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(
            f"| [`{row.source_id}`]({row.source_url}) | {_md_escape(row.publisher)} | "
            f"`{row.scheme_id}` | `{row.doc_type}` | {row.chunk_count} | {row.token_total} | "
            f"{row.retrieved_at} |"
        )
    lines.append("")
    return "\n".join(lines)


def export(chunks: list[Chunk] | None = None) -> tuple[Path, Path]:
    """Write both manifests and return their paths."""
    rows = aggregate(chunks if chunks is not None else _read_chunks())

    MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=SOURCES_CSV_HEADER)
        writer.writeheader()
        for row in rows:
            writer.writerow(row.as_csv())

    MD_PATH.write_text(render_markdown(rows, chunks if chunks is not None else _read_chunks()), encoding="utf-8")
    return CSV_PATH, MD_PATH


def _read_chunks() -> list[Chunk]:
    from src.ingest.build_index import read_chunks

    if not CHUNKS_PATH.exists():
        raise FileNotFoundError(
            f"{CHUNKS_PATH} does not exist. Run `python -m src.ingest.build_index "
            f"--stage chunk` before exporting."
        )
    return read_chunks()
